name: stable

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7, '3.0', 3.1, 3.2, ruby-head, jruby-9.3]

    env:
      BUNDLE_WITHOUT: "benchmark"
      JRUBY_OPTS: "--debug"

    steps:
      - uses: actions/checkout@v3

      - name: Get sqlite for Rails test projects
        run: sudo apt-get install libsqlite3-dev

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache

      - name: Get the newest rubygems version to rid ourselves of warnings
        run: gem update --system --no-document

      - name: Run tests
        run: bundle exec rake
