name: unstable

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ruby-head, jruby-head]

    env:
      BUNDLE_WITHOUT: "benchmark"
      JRUBY_OPTS: "--debug"

    steps:
      - uses: actions/checkout@v3

      - name: Get sqlite for Rails test projects
        run: sudo apt-get install libsqlite3-dev

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache

      - name: Install dependencies
        run: |
          bundle config set --local without benchmark
          bundle install --jobs=3

      - name: Run tests
        run: bundle exec rake
